# IMDB Sentiment Analysis

In [2]:
import pandas as pd
df = pd.read_csv('/Users/aryanvijaykumar/Downloads/IMDB Dataset.csv')

In [3]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

count =  CountVectorizer()

docs = np.array(['The sun is shining',
                'The weather is sweet',
                'The sun is shining, the weatehr is sweet,and one and one is two'])

bag = count.fit_transform(docs)

In [7]:
print(count.vocabulary_)

{'the': 6, 'sun': 4, 'is': 1, 'shining': 3, 'weather': 9, 'sweet': 5, 'weatehr': 8, 'and': 0, 'one': 2, 'two': 7}


In [8]:
print(bag.toarray())

[[0 1 0 1 1 0 1 0 0 0]
 [0 1 0 0 0 1 1 0 0 1]
 [2 3 2 1 1 1 2 1 1 0]]
